sudo: required
language: go

services:
  - docker

go:
  - master

before_install:
  - mkdir .keys && openssl aes-256-cbc -K $encrypted_bdb0e2d25710_key -iv $encrypted_bdb0e2d25710_iv -in secrets.tar.enc -out .keys/secrets.tar -d
  - tar xvf .keys/secrets.tar
  - chmod +x deploy.sh

install:
  - go mod download

env: 
  - BBS_DATABASE=database BBS_DATABASE_PORT=5432 BBS_DATABASE_USER=admin BBS_DATABASE_PASSWORD=admin123 BBS_DATABASE_DATABASE=db PRIVATE_KEY_PATH=.keys/app.rsa PUBLIC_KEY_PATH=.keys/app.rsa.pub SECRET_KEY=vivalavinyl GO111MODULE=on

after_success:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && ./deploy.sh
