sudo: required
language: go

services:
  - docker

go:
  - master

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

env: 
  - BBS_DATABASE=database BBS_DATABASE_PORT=5432 BBS_DATABASE_USER=admin BBS_DATABASE_PASSWORD=admin123 BBS_DATABASE_DATABASE=db PRIVATE_KEY_PATH=.keys/app.rsa PUBLIC_KEY_PATH=.keys/app.rsa.pub SECRET_KEY=vivalavinyl

after_success:
  - curl https://cli-assets.heroku.com/install.sh | sh
  - docker login -u _ -p "$HEROKU_TOKEN" registry.heroku.com
  - docker build -t registry.heroku.com/vivalavinyl-service/web .
  - docker push registry.heroku.com/vivalavinyl-service/web 
  - heroku container:release web -a vivalavinyl-service
